# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-28 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kh', '0002_auto_20161022_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='weather',
            name='night',
            field=models.CharField(max_length=20),
        ),
    ]
